Fix untar command

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -16,7 +16,7 @@ release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION"
 download_release "$ASDF_INSTALL_VERSION" "$release_file"
 
 if [ -f "$release_file.tar.gz" ]; then
-	tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+	tar -xzf "$release_file.tar.gz" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file.tar.gz"
 	rm "$release_file.tar.gz"
 fi
 
